# Generated by Django 3.2 on 2022-06-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
    ]
